#ifndef CROW_AST_NODE_NODE_TRAITS_TYPING_INCLUDE_HPP
#define CROW_AST_NODE_NODE_TRAITS_TYPING_INCLUDE_HPP


// Node Traits Typing:
#include "type_data.hpp"

#endif // CROW_AST_NODE_NODE_TRAITS_TYPING_INCLUDE_HPP
